import type { Event, Kvart, User, GameId } from "@/lib/store";

const now = Date.now();
const days = (n: number) => new Date(now + n * 86400_000).toISOString();
const hours = (n: number) => new Date(now + n * 3600_000).toISOString();

export const seedUsers: User[] = [
  { id: "u_frane", displayName: "Frane", kvart: "Veli Varoš", isGuest: false, createdAt: days(-40) },
  { id: "u_ante", displayName: "Ante", kvart: "Lučac", isGuest: false, createdAt: days(-35) },
  { id: "u_sime", displayName: "Šime", kvart: "Manuš", isGuest: false, createdAt: days(-31) },
  { id: "u_jure", displayName: "Jure", kvart: "Bačvice", isGuest: false, createdAt: days(-28) },
  { id: "u_mate", displayName: "Mate", kvart: "Varoš", isGuest: false, createdAt: days(-25) },
  { id: "u_marija", displayName: "Marija", kvart: "Veli Varoš", isGuest: false, createdAt: days(-22) },
  { id: "u_ana", displayName: "Ana", kvart: "Lučac", isGuest: false, createdAt: days(-18) },
  { id: "u_iva", displayName: "Iva", kvart: "Bačvice", isGuest: false, createdAt: days(-15) },
];

export type SeedScore = {
  userId: string;
  userName: string;
  gameId: GameId;
  points: number;
  createdAt: string;
};

// Mix of games + times for daily/weekly/all-time filters
export const seedScores: SeedScore[] = [
  { userId: "u_frane", userName: "Frane", gameId: "briskula", points: 88, createdAt: hours(-2) },
  { userId: "u_frane", userName: "Frane", gameId: "briskula", points: 71, createdAt: hours(-26) },
  { userId: "u_ante", userName: "Ante", gameId: "briskula", points: 95, createdAt: hours(-5) },
  { userId: "u_sime", userName: "Šime", gameId: "briskula", points: 64, createdAt: hours(-30) },
  { userId: "u_jure", userName: "Jure", gameId: "mora", points: 5, createdAt: hours(-1) },
  { userId: "u_mate", userName: "Mate", gameId: "mora", points: 4, createdAt: hours(-12) },
  { userId: "u_marija", userName: "Marija", gameId: "briskula", points: 102, createdAt: hours(-3) },
  { userId: "u_marija", userName: "Marija", gameId: "mora", points: 5, createdAt: hours(-50) },
  { userId: "u_ana", userName: "Ana", gameId: "briskula", points: 78, createdAt: hours(-72) },
  { userId: "u_iva", userName: "Iva", gameId: "briskula", points: 91, createdAt: hours(-8) },
  { userId: "u_iva", userName: "Iva", gameId: "mora", points: 5, createdAt: hours(-20) },
  { userId: "u_frane", userName: "Frane", gameId: "mora", points: 4, createdAt: hours(-100) },
  { userId: "u_ante", userName: "Ante", gameId: "mora", points: 5, createdAt: hours(-200) },
  { userId: "u_jure", userName: "Jure", gameId: "briskula", points: 110, createdAt: hours(-150) },
  { userId: "u_mate", userName: "Mate", gameId: "briskula", points: 82, createdAt: hours(-300) },
];

// Real-ish coordinates around Split
export const seedEvents: Event[] = [
  {
    id: "e_brk_matejuska",
    hostId: "u_frane",
    hostName: "Frane",
    gameId: "briskula",
    title: "Briškula večer kod Matejuške",
    description: "Stara škola briškule, 4 stola, dođi sa prijateljem. Pivo plaća zadnji.",
    startsAt: days(1),
    lat: 43.5085,
    lng: 16.4365,
    locationName: "Konoba Matejuška",
    capacity: 16,
    language: "ck",
    rsvps: ["u_ante", "u_sime"],
  },
  {
    id: "e_brk_varos",
    hostId: "u_mate",
    hostName: "Mate",
    gameId: "briskula",
    title: "Veli Varoš briškula turnir",
    description: "Turnir jedan-na-jedan, ulaz 5 €, pobjednik dobije bocu prošeka.",
    startsAt: days(3),
    lat: 43.5095,
    lng: 16.4341,
    locationName: "Konoba Varoš",
    capacity: 24,
    language: "hr",
    rsvps: ["u_frane", "u_marija", "u_iva"],
  },
  {
    id: "e_brk_bajamonti",
    hostId: "u_ante",
    hostName: "Ante",
    gameId: "briskula",
    title: "Briškula & prošek",
    description: "Mirno veče, dvije ekipe, otvoreno za diasporu i turiste.",
    startsAt: days(5),
    lat: 43.5074,
    lng: 16.4393,
    locationName: "Bajamonti",
    capacity: 12,
    language: "en",
    rsvps: ["u_jure"],
  },
  {
    id: "e_tre_velivaros",
    hostId: "u_marija",
    hostName: "Marija",
    gameId: "treseta",
    title: "Trešeta po starinski",
    description: "Po pravilima Velog Varoša, samo tučem i strišo, ništa drugo.",
    startsAt: days(2),
    lat: 43.5099,
    lng: 16.4325,
    locationName: "Veli Varoš pjaceta",
    capacity: 8,
    language: "ck",
    rsvps: ["u_frane", "u_mate"],
  },
  {
    id: "e_tre_lucac",
    hostId: "u_ana",
    hostName: "Ana",
    gameId: "treseta",
    title: "Trešeta večer u Lučcu",
    description: "Sjedi, šuti, igraj. Dobrodošli početnici, naučit ćemo te.",
    startsAt: days(7),
    lat: 43.5083,
    lng: 16.4475,
    locationName: "Konoba u Lučcu",
    capacity: 10,
    language: "hr",
    rsvps: ["u_iva"],
  },
  {
    id: "e_pic_bacvice_1",
    hostId: "u_jure",
    hostName: "Jure",
    gameId: "picigin",
    title: "Jutarnji picigin na Bačvicama",
    description: "Svaki dan u 7:30, ne planiraj, samo dođi. Loptica je naša.",
    startsAt: hours(15),
    lat: 43.50506,
    lng: 16.45088,
    locationName: "Bačvice plaža",
    capacity: 20,
    language: "hr",
    rsvps: ["u_frane", "u_mate", "u_ante", "u_iva", "u_marija"],
  },
  {
    id: "e_pic_bacvice_2",
    hostId: "u_iva",
    hostName: "Iva",
    gameId: "picigin",
    title: "Picigin za diasporu",
    description: "Diaspora special — naučit ćemo te kako se igra prava bačvička.",
    startsAt: days(4),
    lat: 43.5052,
    lng: 16.452,
    locationName: "Bačvice, istočni kraj",
    capacity: 15,
    language: "en",
    rsvps: [],
  },
  {
    id: "e_pic_znjan",
    hostId: "u_sime",
    hostName: "Šime",
    gameId: "picigin",
    title: "Picigin na Žnjanu",
    description: "Mlađa ekipa, akrobatike, snima se za TikTok.",
    startsAt: days(6),
    lat: 43.50212,
    lng: 16.47338,
    locationName: "Žnjan",
    capacity: 16,
    language: "hr",
    rsvps: ["u_jure"],
  },
  {
    id: "e_bal_marjan",
    hostId: "u_mate",
    hostName: "Mate",
    gameId: "balote",
    title: "Balote popodne na Marjanu",
    description: "Dvije ekipe od tri, kapetani biraju, pjesma između rundi.",
    startsAt: days(2),
    lat: 43.51499,
    lng: 16.41834,
    locationName: "Marjan, stari plac",
    capacity: 12,
    language: "ck",
    rsvps: ["u_frane", "u_ante"],
  },
  {
    id: "e_bal_trstenik",
    hostId: "u_ante",
    hostName: "Ante",
    gameId: "balote",
    title: "Balote u Trsteniku",
    description: "Trsteničke pravila, brže od marjanske ekipe.",
    startsAt: days(4),
    lat: 43.50455,
    lng: 16.4836,
    locationName: "Trstenik",
    capacity: 10,
    language: "hr",
    rsvps: ["u_sime"],
  },
  {
    id: "e_plj_varos",
    hostId: "u_frane",
    hostName: "Frane",
    gameId: "pljockanje",
    title: "Pljočkanje u Varošu",
    description: "Donesi ploke ako ih imaš, ako ne, posudit ćemo. Lek je tvrd kao kamen.",
    startsAt: days(8),
    lat: 43.5104,
    lng: 16.4318,
    locationName: "Varoš plac",
    capacity: 14,
    language: "hr",
    rsvps: [],
  },
  {
    id: "e_mor_riva",
    hostId: "u_marija",
    hostName: "Marija",
    gameId: "mora",
    title: "Mora kantada — otvoreno za sve",
    description: "Mora bez starih pravila — i muški i ženske, svi viču.",
    startsAt: days(3),
    lat: 43.5076,
    lng: 16.4385,
    locationName: "Riva, kraj fontane",
    capacity: 20,
    language: "ck",
    rsvps: ["u_iva", "u_ana"],
  },
  {
    id: "e_brk_manus",
    hostId: "u_sime",
    hostName: "Šime",
    gameId: "briskula",
    title: "Briškula u Manušu",
    description: "Manuš protiv Bačvica, neka pobijedi bolji kvart.",
    startsAt: days(9),
    lat: 43.5126,
    lng: 16.4453,
    locationName: "Manuš",
    capacity: 16,
    language: "hr",
    rsvps: ["u_jure", "u_iva"],
  },
  {
    id: "e_tre_bacvice",
    hostId: "u_jure",
    hostName: "Jure",
    gameId: "treseta",
    title: "Trešeta na terasi (Bačvice)",
    description: "Pogled na more, hladovina, mirno popodne.",
    startsAt: days(11),
    lat: 43.5063,
    lng: 16.4486,
    locationName: "Bačvice terasa",
    capacity: 8,
    language: "hr",
    rsvps: [],
  },
  {
    id: "e_brk_diocletian",
    hostId: "u_iva",
    hostName: "Iva",
    gameId: "briskula",
    title: "Briškula in the Palace (English)",
    description: "Tourist-friendly briškula intro inside the old city. Bring patience.",
    startsAt: days(2),
    lat: 43.5081,
    lng: 16.4402,
    locationName: "Diocletian's Palace courtyard",
    capacity: 10,
    language: "en",
    rsvps: ["u_marija"],
  },
];
